acc_lim_v: 3.0
acc_lim_vth: 1.0
max_v: 2.0
min_v: 0.1
max_vth: 1.0
min_vth: -1.0
min_in_place_vth: 0.4
backup_v: -0.1
v_samples: 10
vth_samples: 10
sim_time: 3.0
sim_period: 0.4
dist_gap: 0.2
ang_gap: 0.03

pdist_weight: 1.5
gdist_weight: 4.3
occcost_weight: 6.0

heading_lookahead: 0.325

oscillation_reset_dist_: 0.05

escape_reset_dist: 0.1
escape_reset_theta: 1.5708
